<?php

/**
 * ======================================================================
 * LICENSE: This file is subject to the terms and conditions defined in *
 * file 'license.txt', which is part of this source code package.       *
 * ======================================================================
 */
?>
<div class="wrap" id="aam">
    <div class="postbox-container" style="width:70%;">
        <div class="metabox-holder">
            <div class="meta-box-sortables">
                <div class="postbox">
                    <div class="handlediv" title="<?php echo __('Click to toggle', 'aam'); ?>"></div>
                    <h3 class="hndle">
                        <span>
                            <?php echo __('AAM ConfigPress', 'aam'); ?>
                        </span>
                    </h3>
                    <div class="inside">
                        <textarea id="configpress" style="width:100%; height: 400px;"><?php echo aam_Core_ConfigPress::read(); ?></textarea>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php if (aam_Core_Console::hasIssues()) { ?>
        <div class="postbox-container" style="width:25%; margin-left: 2%;">
            <div class="metabox-holder">
                <div class="meta-box-sortables">
                    <div class="postbox">
                        <div class="handlediv" title="<?php echo __('Click to toggle', 'aam'); ?>"></div>
                        <h3 class="hndle">
                            <span><?php echo __('AAM Warnings', 'aam'); ?></span>
                        </h3>
                        <div class="inside">
                            <?php foreach (aam_Core_Console::getWarnings() as $warning) { ?>
                                <div class="aam-warning"><span><?php echo $warning; ?></span></div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>

    <div class="postbox-container" style="width:25%; margin-left: 2%;">
        <div class="metabox-holder">
            <div class="meta-box-sortables">
                <div class="postbox" id="control_panel">
                    <div class="handlediv" title="<?php echo __('Click to toggle', 'aam'); ?>"></div>
                    <h3 class="hndle">
                        <span><?php echo __('Control Panel', 'aam'); ?></span>
                    </h3>
                    <div class="inside">
                        <div class="large-icons-row">
                            <a href="#" class="aam-icon aam-icon-large aam-icon-large-save" id="save_config" >
                                <span></span><?php echo __('Save', 'aam'); ?>
                            </a>
                        </div>
                        <div class="medium-icons-row">
                            <a href="https://twitter.com/wpaam" target="_blank" class="aam-icon aam-icon-medium aam-icon-medium-twitter" aam-tooltip="<?php echo __('Follow @wpaam', 'aam'); ?>">
                                <span></span><?php echo __('Follow', 'aam'); ?>
                            </a>
                            <a href="http://wpaam.com/support" target="_blank" class="aam-icon aam-icon-medium aam-icon-medium-help" aam-tooltip="<?php echo __('Help Forum', 'aam'); ?>">
                                <span></span><?php echo __('Help', 'aam'); ?>
                            </a>
                            <a href="mailto:support@wpaam.com" class="aam-icon aam-icon-medium aam-icon-medium-message" id="aam_message" aam-tooltip="<?php echo __('E-mail Us', 'aam'); ?>">
                                <span></span><?php echo __('E-mail Us', 'aam'); ?>
                            </a>
                            <a href="http://wordpress.org/support/view/plugin-reviews/advanced-access-manager" target="_blank" class="aam-icon aam-icon-medium aam-icon-medium-star" aam-tooltip="<?php echo __('Rate AAM', 'aam'); ?>">
                                <span></span><?php echo __('Rate Us', 'aam'); ?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


