<div class="wrap" id="aam">
    <div class="postbox-container" style="width:70%;">
        <div class="metabox-holder">
            <div class="meta-box-sortables">
                <div class="postbox">
                    <div class="handlediv" title="<?php echo __('Click to toggle', 'aam'); ?>"></div>
                    <h3 class="hndle">
                        <span>
                            <?php echo __('Extension List', 'aam'); ?>
                        </span>
                    </h3>
                    <div class="inside">
                        <table id="extension_list">
                            <thead>
                                <tr>
                                    <th width="25%"><?php echo __('Name', 'aam'); ?></th>
                                    <th width="50%"><?php echo __('Description', 'aam'); ?></th>
                                    <th width="10%"><?php echo __('Price', 'aam'); ?></th>
                                    <th><?php echo __('Actions', 'aam'); ?></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <span class="extension-name">AAM Multisite Support</span>
                                    </td>
                                    <td class="extension-description">
                                        Extends the AAM functionality to Multisite support and allow
                                        to control all your multi blogs within one Admin Page. <b>Please notice!</b> 
                                        Extension is currently under development. Follow us on 
                                        <a href="https://twitter.com/wpaam" target="_blank">Twitter</a> to know the
                                        latest updates.
                                    </td>
                                    <td class="extension-price free">Free</td>
                                    <td>
                                        <div class="extension-actions">
                                            <a href="http://wpaam.com/support#viewtopic.php?f=7&t=9" target="_blank" class="extension-action extension-action-forum" tooltip="Visit Our Forum"></a>
                                            <a href="#" class="extension-action extension-action-download development" disabled="disabled" tooltip="Install It Now"></a>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <span class="extension-name">AAM Plus Package</span>
                                    </td>
                                    <td class="extension-description">
                                        Current Extension extends default AAM basic features and unlock some limitations. 
                                        Add custom taxonomy <b>Page Category</b> to ground pages into categories;
                                        Unlock the limitation for Post Access control;
                                        Add additional Capability Group <b>Comments</b> with the set of capabilities to control default comment 
                                        actions like <b>Reply</b>, <b>Mark Spam</b>, <b>Trash</b>, <b>Delete</b> etc;
                                        Add possibility to setup default post or page access.
                                        For more details, please visit our forum.
                                    </td>
                                    <td class="extension-price payed">$30.00</td>
                                    <td>
                                        <div class="extension-actions">
                                            <a href="http://wpaam.com/support#viewtopic.php?f=7&t=10" target="_blank" class="extension-action extension-action-forum" tooltip="Visit Our Forum"></a>
                                            <a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=UEM8U65HFEG4Q" class="extension-action extension-action-purchase" tooltip="Buy it Today" target="_blank"></a>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div id="under_dev" class="aam-dialog" title="<?php echo __('Extension Status', 'aam'); ?>">
                            <p class="dialog-content"><?php echo __('Current Extension is under development. Please follow us on <a href="https://twitter.com/wpaam" target="blank">Twitter</a> to know the latest updates.', 'aam'); ?></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="postbox-container" style="width:25%; margin-left: 2%;">
        <div class="metabox-holder">
            <div class="meta-box-sortables">
                <div class="postbox">
                    <div class="handlediv" title="<?php echo __('Click to toggle', 'aam'); ?>"></div>
                    <h3 class="hndle">
                        <span><?php echo __('Connect with AAM', 'aam'); ?></span>
                    </h3>
                    <div class="inside">
                        <div id="misc-publishing-actions" class="cpanel">
                            <a href="https://twitter.com/wpaam" class="cpanel-item cpanel-item-twitter" tooltip="Follow @wpaam" target="_blank">Follow</a>
                            <a href="mailto:support@wpaam.com" class="cpanel-item cpanel-item-message" tooltip="Send Us Email">Send Message</a>
                            <a href="http://wpaam.com" class="cpanel-item cpanel-item-website" tooltip="Visit Us" target="_blank">Website</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


