<?php
/**
 * ======================================================================
 * LICENSE: This file is subject to the terms and conditions defined in *
 * file 'license.txt', which is part of this source code package.       *
 * ======================================================================
 */
?>
<div id="role_manager_wrap">
    <table id="role_list">
        <thead>
            <tr>
                <th>Role ID</th>
                <th>User Count</th>
                <th width="60%">Role</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

    <div id="manage_role_dialog" class="aam-dialog">
        <table class="dataTable">
            <tbody>
                <tr>
                    <th>Role Name<span class="aam-asterix">*</span>:</th>
                    <td><input type="text" id="role_name" class="aam-input" /></td>
                </tr>
            </tbody>
        </table>
    </div>

    <div id="delete_role_dialog" class="aam-dialog" title="Delete Role">
        <p class="dialog-content"></p>
    </div>
</div>