<?php
/**
 * ======================================================================
 * LICENSE: This file is subject to the terms and conditions defined in *
 * file 'license.txt', which is part of this source code package.       *
 * ======================================================================
 */
?>
<div id="user_manager_wrap">
    <table id="user_list">
        <thead>
            <tr>
                <th>User ID</th>
                <th>User Login</th>
                <th width="60%">Username</th>
                <th>Action</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

    <div id="filter_user_dialog" class="aam-dialog" title="Filter Users by Role">
        <table id="filter_role_list">
            <thead>
                <tr>
                    <th>Role ID</th>
                    <th>User Count</th>
                    <th width="80%">Role Name</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>

    <div id="delete_user_dialog" class="aam-dialog" title="Delete User">
        <span class="dialog-content"></span>
    </div>
</div>