<div class="aam-feature" id="capability-content">
    <div class="aam-feature-top-actions text-right">
        <div class="btn-group">
            <a href="#" class="btn btn-xs btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="capability-filter">
                <i class="icon-filter"></i> <?php echo __('Filter', AAM_KEY); ?> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" id="capability-groups">
                <?php foreach ($this->getGroupList() as $group) { ?>
                    <li><a href="#"><?php echo $group; ?></a></li>
                <?php } ?>
                <li role="separator" class="divider"></li>
                <li><a href="#" data-clear="true"><?php echo __('All Capabilities', AAM_KEY); ?></a></li>
            </ul>
        </div>
        <a href="#" class="btn btn-xs btn-primary" id="add-capability"><i class="icon-plus"></i> <?php echo __('Create', AAM_KEY); ?></a>
    </div>

    <table id="capability-list" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th width="35%"><?php echo __('Category', AAM_KEY); ?></th>
                <th width="50%"><?php echo __('Capability', AAM_KEY); ?></th>
                <th><?php echo __('Assign', AAM_KEY); ?></th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

    <div class="modal fade" id="add-capability-modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"><?php echo __('Add New Capability', AAM_KEY); ?></h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="new-capability-name"><?php echo __('Capability Name', AAM_KEY); ?><span class="aam-asterix">*</span></label>
                        <input type="text" class="form-control" id="new-capability-name" placeholder="<?php echo __('Enter Capability', AAM_KEY); ?>" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success" id="add-capability-btn"><?php echo __('Add Capability', AAM_KEY); ?></button>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Close', AAM_KEY); ?></button>
                </div>
            </div>
        </div>
    </div>
</div>