<div class="aam-feature" id="extension-content">
    <div class="row">
        <div class="col-xs-12">
            <p class="aam-info">
                <?php echo AAM_Backend_Helper::preparePhrase('One license is limited to one domain only but it can be used for unlimited number of test or development environments where URL is either [localhost] or starts with [dev.], [staging.] or [test.]', 'i', 'i', 'i', 'i'); ?>
            </p>
        </div>
    </div>
    
    <div class="row">
        <div class="col-xs-8">
            <div class="form-group">
                <input type="text" class="form-control" id="extension-key" placeholder="<?php echo __('License Key or PayPal Transaction ID', AAM_KEY); ?>" />
            </div>
        </div>
        <div class="col-xs-4">
            <button class="btn btn-primary btn-block" id="install-extension"><i class="icon-download-cloud"></i> <?php echo __('Install', AAM_KEY); ?></button>
        </div>
    </div>

    <table class="table table-striped table-bordered" id="extension-list">
        <thead>
            <tr>
                <th width="80%"><?php echo __('Extension', AAM_KEY); ?></th>
                <th><?php echo __('Action', AAM_KEY); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php $plusPackage = $this->extensionStatus('AAM Plus Package'); ?>
            <?php if ($plusPackage !== self::STATUS_INSTALLED) { ?>
                <tr>
                    <td>
                        <strong>AAM Plus Package - $30</strong>
                        <p class="text-justify">
                            <?php echo __('Unlock limitations related to Posts and Pages feature. Extend basic AAM functionality with Page Categories and ability to manage access to your comments (AAM Plus Package adds new capabilities to the default list of WordPress capabilities like Edit Comments, Delete Comments, Spam Comments etc.).', AAM_KEY); ?>
                        </p>
                    </td>
                    <td>
                        <?php if ($plusPackage == self::STATUS_UPDATE) { ?>
                            <a href="#" class="btn btn-success btn-block aam-update-extension" data-product="AAM Plus Package"><i class="icon-arrows-cw"></i> <?php echo __('Update', AAM_KEY); ?></a>
                        <?php } else { ?>
                            <a href="#purchase-notification-modal" class="btn btn-success btn-block" data-toggle="modal"><i class="icon-basket"></i> <?php echo __('Purchase', AAM_KEY); ?></a>
                        <?php } ?>
                    </td>
                </tr>
            <?php } ?>
            <tr id="extension-list-empty" class="hidden">
                <td colspan="2">
                    <p class="aam-notification-message text-center">
                        <?php echo __('All extensions are installed and up to date.', AAM_KEY); ?>
                    </p>
                </td>
            </tr>
        </tbody>
    </table>

    <div class="modal fade" id="extension-notification-modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"><?php echo __('Notification', AAM_KEY); ?></h4>
                </div>
                <div class="modal-body">
                    <p class="text-center aam-notification-message">
                        <strong><span id="installation-error"></span></strong>. <?php echo sprintf(__('Click "Download" button below for a manual installation or update. Simply unzip the archive to wp-content%s directory.', AAM_KEY), AAM_Core_Repository::RELPATH); ?>
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success" id="download-extension"><?php echo __('Download', AAM_KEY); ?></button>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Cancel', AAM_KEY); ?></button>
                </div>
            </div>
        </div>
    </div>
    
    <div class="modal fade" id="purchase-notification-modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title"><?php echo __('Notification', AAM_KEY); ?></h4>
                </div>
                <div class="modal-body">
                    <p class="text-center aam-notification-message">
                        Extension purchase will be available with the first stable release of AAM version 3. If you already have license purchased for AAM version 2, please fill free to use it, but only for one live domain.
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Close', AAM_KEY); ?></button>
                </div>
            </div>
        </div>
    </div>
    
</div>