<div class="wrap">
    <?php if (AAM_Core_Console::hasIssues()) { ?>
        <div class="row aam-no-margin">
            <div class="col-xs-12">
                <div class="row aam-notification">
                    <div class="col-xs-4 col-md-2 aam-notification-icon">
                        <i class="icon-attention-circled"></i>
                    </div>
                    <div class="col-xs-8 col-md-10 aam-notification-content">
                        <ul class="aam-error-list">
                            <?php foreach (AAM_Core_Console::getWarnings() as $message) { ?>
                                <li><?php echo $message; ?></li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <h1 class="aam-current-subject"></h1>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-md-8">
            <div class="metabox-holder">
                <div class="postbox">
                    <h3 class="hndle">
                        <span><?php echo __('Access Manager', AAM_KEY); ?></span> <small><span class="text-warning text-uppercase">Beta Version</span></small>
                        <span class="aam-help-menu" data-target="#access-manager-inside"><i class="icon-help-circled"></i></span>
                    </h3>
                    <div class="inside" id="access-manager-inside">
                        <div class="aam-postbox-inside" id="aam-content"></div>
                        <div class="aam-help-context" >
                            <p class="aam-info aam-hint">
                                <strong><?php echo __('Note from the author', AAM_KEY); ?></strong><br/>
                                <?php echo __('Appreciate your interest in Advanced Access Manager (aka AAM). With a strong knowledge and experience in WordPress, AAM becomes a very powerful tool to manage access to your frontend and backend.', AAM_KEY); ?><br/>
                                <span class="aam-highlight"><?php echo __('Please notice!', AAM_KEY); ?></span> <?php echo AAM_Backend_Helper::preparePhrase('Power comes with responsibility. Make sure that you have enough knowledge in WordPress Roles and Capabilities because AAM is very closely tight to WordPress core. It is also very important [to have backup of your database before you start working with AAM] (there is no need to backup your files, AAM does not modify any physical files on your server and never did).', 'b'); ?><br/> 
                                <?php echo __('AAM was thoroughly tested on the fresh installation of WordPress and in the latest versions of Chrome, Safari, IE and Firefox. If you have any issues, please make sure that there is no conflict with other plugins on your WordPress installation.', AAM_KEY); ?><br/>
                                <?php echo __('Please find below the short description of each feature that AAM offers.', AAM_KEY); ?>
                            </p>

                            <p class="text-justify">
                                <strong><?php echo __('Backend Menu', AAM_KEY); ?></strong><br/>
                                <?php echo __('Filter the admin menu. Please notice that it only filters the menu but does not restrict a direct access to the filtered menus. In order to completely restrict access to the menu, make sure that your role or user does not have capability that is assigned by WordPress core to that menu (the capability name is right next to the menu name).', AAM_KEY); ?>
                            </p>

                            <p class="text-justify">
                                <strong><?php echo __('Metaboxes &amp; Widgets', AAM_KEY); ?></strong><br/>
                                <?php echo __('Filter backend metaboxes and frontend widgets. If the list of metaboxes and widgets is empty, click the “Refresh” button. This will reinitialize the list. It is a possibility that this feature will not work on servers that fails to execute WordPress remote request function “wp_remote_request”.', AAM_KEY); ?>
                            </p>

                            <p class="text-justify">
                                <strong><?php echo __('Capabilities', AAM_KEY); ?></strong><br/>
                                <?php echo __('This is probably the most important and powerful feature that manages list of capabilities for roles and users. Please make sure that you are familiar with WordPress Roles and Capabilities before using this feature. Do not try to un-check any capability for the Administrator role because your might lose access to your backend. While creating a new capability, AAM takes the capability name without any additional processing or normalization; which means that if you created new capability “Manage Boats”, internally it retains the same exact name.', AAM_KEY); ?>
                            </p>

                            <p class="text-justify">
                                <strong><?php echo __('Posts &amp; Pages', AAM_KEY); ?></strong><br/>
                                <?php echo __('Manage access to your posts, pages and custom post types.', AAM_KEY); ?> <span class="aam-highlight"><?php echo __('Please notice!', AAM_KEY); ?></span> <?php echo __('This feature has limitations without AAM Plus Package extension.', AAM_KEY); ?>
                            </p>

                            <p class="text-justify">
                                <strong><?php echo __('Extensions', AAM_KEY); ?></strong><br/>
                                <?php echo sprintf(__('Extend AAM functionality with variety of extensions that can be either downloaded for free or purchased. All payment transactions are handled securely through PayPal and the PayPal Transaction ID is used to obtain the purchased extension (you can find Transaction ID in the email that PayPal send you after the purchase). Most of the time the extension is available for download almost immediately but it might take up to 2 hours for PayPal to notify our server about your payment. You are allowed to get the full refund within 30 days after the purchase, if extension did not meet your expectation. Please submit the %srefund form%s and we will issue a refund within next 3 business days.', AAM_KEY), '<a href="http://vasyltech/advanced-access-manager" target="_blank">', '</a>'); ?>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xs-12 col-md-4">
            <div class="metabox-holder">
                <?php do_action('aam-sidebar-ui-action', 'top'); ?>

                <div class="postbox">
                    <h3 class="hndle">
                        <span><?php echo __('User/Role Manager', AAM_KEY); ?></span>
                        <span class="aam-help-menu" data-target="#user-role-manager-inside"><i class="icon-help-circled"></i></span>
                    </h3>
                    <div class="inside" id="user-role-manager-inside">
                        <div class="aam-postbox-inside">
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="active"><a href="#roles" aria-controls="roles" role="tab" data-toggle="tab"><i class="icon-users"></i> <?php echo __('Roles', AAM_KEY); ?></a></li>
                                <li role="presentation"><a href="#users" aria-controls="users" role="tab" data-toggle="tab"><i class="icon-user"></i> <?php echo __('Users', AAM_KEY); ?></a></li>
                                <li role="presentation"><a href="#visitor" aria-controls="visitor" role="tab" data-toggle="tab"><i class="icon-user-secret"></i> <?php echo __('Visitor', AAM_KEY); ?></a></li>
                            </ul>
                            <div class="tab-content">
                                <div role="tabpanel" class="tab-pane active" id="roles">
                                    <table id="role-list" class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Users</th>
                                                <th width="70%"><?php echo __('Role', AAM_KEY); ?></th>
                                                <th><?php echo __('Action', AAM_KEY); ?></th>
                                            </tr>
                                        </thead>
                                        <tbody></tbody>
                                    </table>

                                    <div class="modal fade" id="add-role-modal" tabindex="-1" role="dialog">
                                        <div class="modal-dialog modal-sm" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                                                    <h4 class="modal-title"><?php echo __('Add New Role', AAM_KEY); ?></h4>
                                                </div>
                                                <div class="modal-body">
                                                    <div class="form-group">
                                                        <label for="new-role-name"><?php echo __('Role Name', AAM_KEY); ?><span class="aam-asterix">*</span></label>
                                                        <input type="text" class="form-control" id="new-role-name" placeholder="<?php echo __('Enter Role Name', AAM_KEY); ?>" />
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="inherit-role-list"><?php echo __('Inherit Capabilities', AAM_KEY); ?></label>
                                                        <select class="form-control" id="inherit-role-list">
                                                            <option value=""><?php echo __('Select Role', AAM_KEY); ?></option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-success" id="add-role-btn"><?php echo __('Add Role', AAM_KEY); ?></button>
                                                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Close', AAM_KEY); ?></button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="modal fade" id="edit-role-modal" tabindex="-1" role="dialog">
                                        <div class="modal-dialog modal-sm" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                                                    <h4 class="modal-title"><?php echo __('Edit Role', AAM_KEY); ?></h4>
                                                </div>
                                                <div class="modal-body">
                                                    <div class="form-group">
                                                        <label for="new-role-name"><?php echo __('Role Name', AAM_KEY); ?></label>
                                                        <input type="text" class="form-control" id="edit-role-name" placeholder="<?php echo __('Enter Role Name', AAM_KEY); ?>" />
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-success" id="edit-role-btn"><?php echo __('Update Role', AAM_KEY); ?></button>
                                                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Close', AAM_KEY); ?></button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="modal fade" id="delete-role-modal" tabindex="-1" role="dialog">
                                        <div class="modal-dialog modal-sm" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                                                    <h4 class="modal-title"><?php echo __('Delete Role', AAM_KEY); ?></h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p class="text-center aam-confirm-message" data-message="<?php echo __('Are you sure that you want to delete %s role?', AAM_KEY); ?>"></p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-danger" id="delete-role-btn"><?php echo __('Delete Role', AAM_KEY); ?></button>
                                                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('Close', AAM_KEY); ?></button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="modal fade" id="role-notification-modal" tabindex="-1" role="dialog">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                                                    <h4 class="modal-title"><?php echo __('Notification', AAM_KEY); ?></h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p class="text-center aam-notification-message"><?php echo __('You are not allowed to delete this role because there is at least one user assigned to it.', AAM_KEY); ?></p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('OK', AAM_KEY); ?></button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <div role="tabpanel" class="tab-pane" id="users">
                                    <table id="user-list" class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Roles</th>
                                                <th width="70%"><?php echo __('Username', AAM_KEY); ?></th>
                                                <th><?php echo __('Action', AAM_KEY); ?></th>
                                            </tr>
                                        </thead>
                                        <tbody></tbody>
                                    </table>

                                    <div class="modal fade" id="user-notification-modal" tabindex="-1" role="dialog">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="<?php echo __('Close', AAM_KEY); ?>"><span aria-hidden="true">&times;</span></button>
                                                    <h4 class="modal-title"><?php echo __('Notification', AAM_KEY); ?></h4>
                                                </div>
                                                <div class="modal-body">
                                                    <p class="text-center aam-notification-message"><?php echo __('You are not allowed to block yourself.', AAM_KEY); ?></p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo __('OK', AAM_KEY); ?></button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                                <div role="tabpanel" class="tab-pane" id="visitor">
                                    <div class="visitor-message">
                                        <span><?php echo __('Manage access to your website for visitors (any user that is not authenticated)', AAM_KEY); ?>.</span>
                                        <button class="btn btn-primary btn-block" id="manage-visitor"><i class="icon-cog"></i> <?php echo __('Manage Visitor', AAM_KEY); ?></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="aam-help-context">
                            <p class="aam-info aam-hint">
                                <?php echo AAM_Backend_Helper::preparePhrase('Manage access for your users, roles and visitors. Please be careful with Administrator role as well as your admin user. [Database backup is strongly recommended]', 'b'); ?>
                            </p>

                            <p class="text-justify">
                                <strong><?php echo __('Role Manager', AAM_KEY); ?></strong><br/>
                                <?php echo __('With role manager you can manage access for any defined role, edit role\'s name, create new role or even delete existing (but only when there is no users assigned to it). You are not allowed to delete Administrator role.', AAM_KEY); ?>
                            </p>

                            <p class="text-justify">
                                <strong><?php echo __('User Manager', AAM_KEY); ?></strong><br/>
                                <?php echo __('Manage access for any user. As a bonus feature, you can block user. It means that user will be not able to login to your website anymore. Create or edit user actions link to the native WordPress create/edit user interface.', AAM_KEY); ?>
                            </p>

                            <p class="text-justify">
                                <strong><?php echo __('Visitor Manager', AAM_KEY); ?></strong><br/>
                                <?php echo __('Visitor is any user that is not authenticated to your website. Considering the fact that visitors do not have any access to backend, any features that ara backend related are disabled.', AAM_KEY); ?>
                            </p>
                        </div>
                    </div>
                </div>
                <?php do_action('aam-sidebar-ui-action', 'bottom'); ?>
            </div>
        </div>
    </div>
</div>

<div class="aam-welcome-message">
    <h1><?php echo AAM_Backend_Helper::preparePhrase('Welcome to [Advanced Access Manager] [(aka AAM)]', 'strong', 'small'); ?></h1>

    <p class="aam-info aam-margin-top-xs">
        <?php echo sprintf(__('Follow us on twitter %s for the latest Advanced Access Manager news.', AAM_KEY), '<strong><a href="https://twitter.com/vasyltech/" target="_blank">@vasyltech</a></strong>'); ?>
    </p>

    <h2 class="aam-margin-top-xs"><?php echo __('What\'s New', AAM_KEY); ?></h2>
    <ul>
        <li><?php echo __('Brand new and much more intuitive user interface.', AAM_KEY); ?></li>
        <li><?php echo __('Fully responsive design so you can manage access to website even on your smart phone.', AAM_KEY); ?></li>
        <li><?php echo __('Better, more reliable and faster core functionality.', AAM_KEY); ?></li>
        <li><?php echo __('Completely new extension handler. In case of any file system failure, you can download an extension for manual installation.', AAM_KEY); ?></li>
        <li><?php echo __('Added "Manage Access" action to the list of user.', AAM_KEY); ?></li>
    </ul>

    <h2 class="aam-highlight aam-margin-top-xs"><?php echo __('Please be aware of the latest changes!', AAM_KEY); ?></h2>
    <ul>
        <li><?php echo __('"Save" button has been removed. Any changes that you perform are saved automatically.', AAM_KEY); ?></li>
        <li><?php echo sprintf('With the first release of AAM version 3, not all extensions from AAM version 2 available for download. More extensions are coming soon. Follow us on twitter %s for the latest news.', '<strong><a href="https://twitter.com/vasyltech/" target="_blank">@vasyltech</a></strong>'); ?></li>
        <li><?php echo __('License key for an extension is valid for one life domain only. All the licenses that were purchased before are still valid but limited to one domain with AAM version 3 (with AAM version 2 it is still unlimited until April 2016).', AAM_KEY); ?></li>
        <li><?php echo __('Development License is valid for 5 domains with AAM version 3 but is still unlimited with version 2 (only until April 2016).', AAM_KEY); ?></li>
        <li><?php echo __('Posts &amp; Pages settings from AAM version 2 are not compatible with AAM version 3.', AAM_KEY); ?></li>
        <li><?php echo __('You are not allowed to delete or lock an "Administrator" role.', AAM_KEY); ?></li>
        <li><?php echo __('There is no longer a "Super Admin" role.', AAM_KEY); ?></li>
        <li><?php echo __('You are not longer allowed to delete any user or group or users (but you still can do it within native WordPress interface).', AAM_KEY); ?></li>
        <li><?php echo __('You are not allowed to delete any capability (even the one that you created manually).', AAM_KEY); ?></li>
    </ul>
    
    <h3>Rollback to AAM version 2</h3>
    <p><?php echo sprintf(__('You can rolleback to the earlier version of AAM by simply downloading any previous version on %sthis page%s. After download, replace the wp-content/plugins/advanced-access-manager directory with the archive\'s content.'), '<a href="https://wordpress.org/plugins/advanced-access-manager/developers/" target="_blank">', '</a>'); ?></p>
    
    <p class="aam-margin-top-xs text-center">
        <a href="#" class="btn btn-lg btn-primary" id="confirm-welcome"><i class="icon-check"></i> <?php echo __('Ok, got it', AAM_KEY); ?></a>
    </p>
</div>